import { SEVERITIES } from '../util/severity.mjs';
import { formatBytes } from '../checks/performance.mjs';

/**
 * A single self-contained HTML file, because a report that needs a build step
 * or a CDN is a report a client cannot open in two years.
 *
 * The report is itself held to the standard it measures: one h1, a heading
 * outline with no skipped levels, a skip link, visible focus on both colour
 * schemes, severity never carried by colour alone, a keyboard-reachable
 * scroll container for every evidence block, and no JavaScript. An
 * accessibility report that fails an accessibility audit is not an argument
 * anyone should have to have with a client.
 */
export function renderHtml(report) {
  const counts = report.summary.bySeverity;
  const generated = new Date(report.startedAt).toUTCString();

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Site audit: ${esc(hostOf(report.target))}</title>
<style>${STYLE}</style>
</head>
<body>
<a class="skip" href="#content">Skip to report</a>
<header class="masthead">
  <p class="eyebrow">Site audit</p>
  <h1>${esc(report.target)}</h1>
  <p class="meta">${report.summary.pagesAudited} page${report.summary.pagesAudited === 1 ? '' : 's'}
    &middot; ${esc(report.modules.join(', '))}
    &middot; ${esc(generated)}</p>
</header>

<main id="content">
  <section aria-labelledby="summary-heading">
    <h2 id="summary-heading">Summary</h2>
    <ul class="tiles">
      ${SEVERITIES.filter((s) => s !== 'info')
        .map(
          (s) => `<li class="tile sev-${s}">
        <span class="tile-value">${counts[s] ?? 0}</span>
        <span class="tile-label">${s}</span>
      </li>`,
        )
        .join('\n      ')}
      <li class="tile sev-manual">
        <span class="tile-value">${report.summary.manualChecksOutstanding}</span>
        <span class="tile-label">manual checks outstanding</span>
      </li>
    </ul>
    <p class="note">There is deliberately no single score here. A percentage invites a client to
      chase the number rather than the failures, and no honest percentage exists while roughly
      two thirds of the accessibility criteria on this page can only be judged by a person.</p>
  </section>

  <section aria-labelledby="budget-heading">
    <h2 id="budget-heading">Budgets</h2>
    <table>
      <caption class="visually-hidden">Budget results by module and metric</caption>
      <thead><tr><th scope="col">Check</th><th scope="col">Result</th><th scope="col">Measured</th><th scope="col">Limit</th></tr></thead>
      <tbody>
      ${report.budget.results
        .map(
          (r) => `<tr>
        <th scope="row"><code>${esc(r.module)}.${esc(r.metric)}</code></th>
        <td><span class="pill ${r.passed ? 'pill-pass' : 'pill-fail'}">${r.passed ? 'Pass' : 'Fail'}</span></td>
        <td>${esc(fmt(r.actual, r.unit))}</td>
        <td>${esc(fmt(r.limit, r.unit))}</td>
      </tr>`,
        )
        .join('\n      ')}
      </tbody>
    </table>
  </section>

  ${report.pages.map((page) => renderPage(page, report.pages.length > 1)).join('\n')}

  ${renderManual(report)}
</main>

<footer>
  <p>Generated by <strong>site-audit-cli ${esc(report.tool.version)}</strong> in
    ${(report.durationMs / 1000).toFixed(1)}s. Automated results reflect one cold load from one
    location on one connection. They are a floor, not a verdict.</p>
</footer>
</body>
</html>`;
}

function renderPage(page, showUrl) {
  const id = `page-${slug(page.url)}`;
  const defects = page.findings.filter((f) => f.kind !== 'manual' && f.severity !== 'info');
  const context = page.findings.filter((f) => f.kind !== 'manual' && f.severity === 'info');

  return `  <section aria-labelledby="${id}">
    <h2 id="${id}">${showUrl ? esc(page.url) : 'Findings'}</h2>
    ${page.metrics ? renderMetrics(page.metrics) : ''}
    ${
      defects.length === 0
        ? '<p class="note">No automated findings on this page. See the manual checks below before treating that as a pass.</p>'
        : defects.map(renderFinding).join('\n    ')
    }
    ${context.length > 0 ? `<h3>Context</h3>\n    ${context.map(renderFinding).join('\n    ')}` : ''}
  </section>`;
}

function renderMetrics(m) {
  const rows = [
    ['Largest Contentful Paint', m.lcpMs === null ? 'not measured' : `${Math.round(m.lcpMs)}ms`],
    ['Cumulative Layout Shift', m.cls.toFixed(3)],
    ['Total Blocking Time', `${Math.round(m.tbtMs)}ms`],
    ['Time to First Byte', `${Math.round(m.ttfbMs)}ms`],
    ['First Contentful Paint', m.fcpMs === null ? 'not measured' : `${Math.round(m.fcpMs)}ms`],
    ['Transfer size', `${formatBytes(m.totalBytes)} over ${m.requestCount} requests`],
  ];
  return `<h3>Lab metrics</h3>
    <dl class="metrics">
      ${rows.map(([k, v]) => `<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('\n      ')}
    </dl>
    <p class="note">Total Blocking Time stands in for Interaction to Next Paint, which cannot be
      measured without a real interaction. Field data from Chrome UX Report is the only source
      that describes actual visitors.</p>`;
}

function renderFinding(f) {
  return `<article class="finding sev-${f.severity}">
      <h3 class="finding-title">
        <span class="sev-tag">${esc(f.severity)}</span>
        ${esc(f.title)}${f.count > 1 ? ` <span class="count">${f.count} instances</span>` : ''}
      </h3>
      <p>${esc(f.detail)}</p>
      ${f.wcag.length > 0 ? `<p class="wcag">WCAG ${esc(f.wcag.join(', '))}</p>` : ''}
      ${f.evidence ? `<pre tabindex="0" role="group" aria-label="Evidence"><code>${esc(f.evidence)}</code></pre>` : ''}
      ${f.help ? `<p class="help"><strong>Next step.</strong> ${linkify(f.help)}</p>` : ''}
    </article>`;
}

function renderManual(report) {
  const manual = report.pages[0]?.findings.filter((f) => f.kind === 'manual') ?? [];
  if (manual.length === 0) return '';
  return `  <section aria-labelledby="manual-heading">
    <h2 id="manual-heading">Checks no scanner can make</h2>
    <p class="note">These are not findings and nothing above counts them. They are the WCAG 2.2
      Level A and AA requirements that no automated tool can decide, listed so that a clean
      automated report is not read as a conformant site.</p>
    ${manual
      .map(
        (m) => `<article class="finding sev-manual">
      <h3 class="finding-title"><span class="sev-tag">manual</span> ${esc(
        m.title.replace('Manual check required: ', ''),
      )} <span class="count">WCAG ${esc(m.wcag.join(', '))}</span></h3>
      <p><strong>Why a scanner cannot decide it.</strong> ${esc(m.detail)}</p>
      <p><strong>How to test.</strong> ${esc(m.help)}</p>
    </article>`,
      )
      .join('\n    ')}
  </section>`;
}

const STYLE = `
:root {
  color-scheme: light dark;
  --bg: #fbfbfd;
  --surface: #ffffff;
  --ink: #16181d;
  --ink-soft: #545a66;
  --line: #e2e5eb;
  --accent: #1f4ed8;
  --critical: #a3122b;
  --serious: #b1471a;
  --moderate: #8a6100;
  --minor: #14607a;
  --manual: #4a4f5c;
  --pass: #15653a;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #0e1014;
    --surface: #161a21;
    --ink: #e9ecf2;
    --ink-soft: #a0a7b6;
    --line: #2a303b;
    --accent: #8fb0ff;
    --critical: #ff8b9d;
    --serious: #ffab7a;
    --moderate: #e8c35e;
    --minor: #7fd4ee;
    --manual: #b3bac7;
    --pass: #6fd79b;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font: 16px/1.62 ui-sans-serif, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  -webkit-text-size-adjust: 100%;
}
.skip {
  position: absolute; left: -9999px; top: 0;
  background: var(--accent); color: #fff; padding: .7rem 1.1rem; z-index: 10;
}
.skip:focus { left: 0; }
:focus-visible { outline: 3px solid var(--accent); outline-offset: 2px; border-radius: 3px; }
.masthead {
  padding: 3rem 1.25rem 2.25rem;
  max-width: 62rem; margin: 0 auto;
  border-bottom: 1px solid var(--line);
}
.eyebrow {
  margin: 0 0 .35rem; text-transform: uppercase; letter-spacing: .13em;
  font-size: .72rem; font-weight: 700; color: var(--ink-soft);
}
h1 { margin: 0 0 .6rem; font-size: clamp(1.5rem, 4vw, 2.1rem); line-height: 1.25; word-break: break-word; }
.meta { margin: 0; color: var(--ink-soft); font-size: .9rem; }
main { max-width: 62rem; margin: 0 auto; padding: 0 1.25rem 4rem; }
section { padding: 2.25rem 0; border-bottom: 1px solid var(--line); }
section:last-of-type { border-bottom: 0; }
h2 { font-size: 1.32rem; margin: 0 0 1.1rem; letter-spacing: -0.01em; }
h3 { font-size: 1.02rem; margin: 1.6rem 0 .6rem; }
.note {
  color: var(--ink-soft); font-size: .92rem; max-width: 60ch;
  border-left: 3px solid var(--line); padding-left: .9rem; margin: 1.1rem 0 0;
}
.tiles { list-style: none; display: flex; flex-wrap: wrap; gap: .7rem; margin: 0; padding: 0; }
.tile {
  flex: 1 1 8rem; background: var(--surface); border: 1px solid var(--line);
  border-radius: 12px; padding: 1rem; display: flex; flex-direction: column; gap: .2rem;
}
.tile-value { font-size: 1.85rem; font-weight: 700; line-height: 1; font-variant-numeric: tabular-nums; }
.tile-label { font-size: .78rem; color: var(--ink-soft); text-transform: uppercase; letter-spacing: .07em; }
.tile.sev-critical .tile-value { color: var(--critical); }
.tile.sev-serious .tile-value { color: var(--serious); }
.tile.sev-moderate .tile-value { color: var(--moderate); }
.tile.sev-minor .tile-value { color: var(--minor); }
.tile.sev-manual .tile-value { color: var(--manual); }
table { width: 100%; border-collapse: collapse; font-size: .92rem; }
caption { text-align: left; }
th, td { text-align: left; padding: .65rem .7rem; border-bottom: 1px solid var(--line); vertical-align: top; }
thead th { font-size: .75rem; text-transform: uppercase; letter-spacing: .07em; color: var(--ink-soft); }
tbody th { font-weight: 500; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .88em; }
.pill {
  display: inline-block; padding: .12rem .55rem; border-radius: 999px;
  font-size: .75rem; font-weight: 700; border: 1px solid currentColor;
}
.pill-pass { color: var(--pass); }
.pill-fail { color: var(--critical); }
.finding {
  background: var(--surface); border: 1px solid var(--line);
  border-left: 4px solid var(--manual); border-radius: 10px;
  padding: 1.05rem 1.15rem; margin: .8rem 0;
}
.finding.sev-critical { border-left-color: var(--critical); }
.finding.sev-serious { border-left-color: var(--serious); }
.finding.sev-moderate { border-left-color: var(--moderate); }
.finding.sev-minor { border-left-color: var(--minor); }
.finding p { margin: .5rem 0; max-width: 68ch; }
.finding-title { margin: 0; font-size: 1rem; display: flex; flex-wrap: wrap; align-items: baseline; gap: .5rem; }
.sev-tag {
  font-size: .68rem; font-weight: 800; text-transform: uppercase; letter-spacing: .09em;
  border: 1px solid currentColor; border-radius: 4px; padding: .05rem .4rem;
}
.sev-critical .sev-tag { color: var(--critical); }
.sev-serious .sev-tag { color: var(--serious); }
.sev-moderate .sev-tag { color: var(--moderate); }
.sev-minor .sev-tag { color: var(--minor); }
.sev-manual .sev-tag { color: var(--manual); }
.count, .wcag { font-size: .78rem; color: var(--ink-soft); font-weight: 500; }
pre {
  background: var(--bg); border: 1px solid var(--line); border-radius: 8px;
  padding: .7rem .8rem; overflow-x: auto; font-size: .82rem; margin: .6rem 0;
}
.help { font-size: .92rem; color: var(--ink-soft); }
a { color: var(--accent); }
.metrics { display: flex; flex-wrap: wrap; gap: .7rem; margin: 0; }
.metrics > div {
  flex: 1 1 10rem; background: var(--surface); border: 1px solid var(--line);
  border-radius: 10px; padding: .8rem .9rem;
}
.metrics dt { font-size: .74rem; text-transform: uppercase; letter-spacing: .07em; color: var(--ink-soft); }
.metrics dd { margin: .25rem 0 0; font-size: 1.15rem; font-weight: 600; font-variant-numeric: tabular-nums; }
footer {
  max-width: 62rem; margin: 0 auto; padding: 1.5rem 1.25rem 3rem;
  border-top: 1px solid var(--line); color: var(--ink-soft); font-size: .86rem;
}
.visually-hidden {
  position: absolute; width: 1px; height: 1px; overflow: hidden;
  clip: rect(0 0 0 0); clip-path: inset(50%); white-space: nowrap;
}
@media print {
  body { background: #fff; }
  .finding, .tile, .metrics > div { break-inside: avoid; }
  .skip { display: none; }
}
`;

function esc(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function linkify(text) {
  const safe = esc(text);
  return /^https?:\/\/\S+$/.test(String(text))
    ? `<a href="${safe}" rel="noopener noreferrer">${safe}</a>`
    : safe;
}

function hostOf(url) {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
}

function slug(url) {
  return String(url).replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').slice(0, 60).toLowerCase();
}

function fmt(value, unit) {
  if (unit === 'bytes') return formatBytes(Number(value));
  if (unit === 'ms') return `${Math.round(Number(value))}ms`;
  if (unit === 'score') return Number(value).toFixed(3);
  return String(value);
}
